version: '2'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: []
    ports:
      - "3030:80"
    volumes:
      - ./backend:/backend
    links:
      - redis:redis
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
  redis:
    container_name: database
    image: redis
    ports:
      - "6379:6379"
