version: '2'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: []
    ports:
      - "3030:80"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zetis
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ../LaboratoriumPAMiW/database:/docker-entrypoint-initdb.d

volumes:
  postgres:
