version: '2'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: []
    ports:
      - "3030:80"
    volumes:
      - ./backend:/backend
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
