version: '2'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "3030:80"
    volumes:
      - ./app:/app
