version: '2'
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: []
    ports:
      - "3000:80"
    volumes:
      - ./app:/app
